import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { Capsule, Item } from "@shared/schema";

interface MeasurementValue {
  value: string;
  unit?: string;
}

type Measurements = Record<string, MeasurementValue> | null | undefined;

export function exportCapsuleToPDF(
  capsule: Capsule,
  items: Item[],
  userMeasurements?: Measurements,
) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  doc.text("Closana", 14, 15);

  doc.setFontSize(20);
  doc.setTextColor(30, 30, 30);
  doc.text(capsule.name, 14, 28);

  let y = 36;
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  const details: string[] = [];
  if (capsule.capsuleCategory) details.push(capsule.capsuleCategory);
  if (capsule.season) details.push(capsule.season);
  if (capsule.useCase) details.push(capsule.useCase);
  if (capsule.style) details.push(capsule.style);
  if (details.length > 0) {
    doc.text(details.join("  |  "), 14, y);
    y += 8;
  }

  doc.text(`${items.length} items`, 14, y);
  y += 10;

  const categorySlots = (capsule.categorySlots as Record<string, number>) || {};
  const categoriesWithItems = Object.keys(categorySlots).filter(
    (cat) => (categorySlots[cat] || 0) > 0,
  );

  if (categoriesWithItems.length > 0) {
    doc.setFontSize(12);
    doc.setTextColor(30, 30, 30);
    doc.text("Category Breakdown", 14, y);
    y += 6;

    const categoryRows = categoriesWithItems.map((cat) => {
      const filled = items.filter((i) => i.category === cat).length;
      const total = categorySlots[cat] || 0;
      return [cat, `${filled} / ${total}`];
    });

    autoTable(doc, {
      startY: y,
      head: [["Category", "Filled / Slots"]],
      body: categoryRows,
      theme: "grid",
      headStyles: { fillColor: [80, 80, 80], fontSize: 9 },
      bodyStyles: { fontSize: 9 },
      margin: { left: 14, right: 14 },
    });

    y = (doc as any).lastAutoTable.finalY + 10;
  }

  if (items.length > 0) {
    doc.setFontSize(12);
    doc.setTextColor(30, 30, 30);
    doc.text("Items", 14, y);
    y += 6;

    const itemRows = items.map((item) => {
      const costPerWear =
        item.price && item.wearCount > 0
          ? `$${(parseFloat(item.price) / item.wearCount).toFixed(2)}`
          : item.wearCount === 0 && item.price
            ? "Not yet worn"
            : "-";
      return [
        item.name,
        item.category,
        item.color || "-",
        item.size || "-",
        item.material || "-",
        String(item.wearCount || 0),
        costPerWear,
      ];
    });

    autoTable(doc, {
      startY: y,
      head: [["Name", "Category", "Color", "Size", "Material", "Wears", "Cost/Wear"]],
      body: itemRows,
      theme: "grid",
      headStyles: { fillColor: [80, 80, 80], fontSize: 8 },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
      columnStyles: {
        0: { cellWidth: 35 },
        5: { cellWidth: 18, halign: "center" },
        6: { cellWidth: 25, halign: "center" },
      },
    });

    y = (doc as any).lastAutoTable.finalY + 10;
  }

  if (userMeasurements && Object.keys(userMeasurements).length > 0) {
    if (y > 250) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(12);
    doc.setTextColor(30, 30, 30);
    doc.text("Measurements", 14, y);
    y += 6;

    const measRows = Object.entries(userMeasurements).map(([key, val]) => [
      key,
      `${val.value}${val.unit ? ` ${val.unit}` : ""}`,
    ]);

    autoTable(doc, {
      startY: y,
      head: [["Measurement", "Value"]],
      body: measRows,
      theme: "grid",
      headStyles: { fillColor: [80, 80, 80], fontSize: 9 },
      bodyStyles: { fontSize: 9 },
      margin: { left: 14, right: 14 },
    });
  }

  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by Closana on ${new Date().toLocaleDateString()}`,
      14,
      doc.internal.pageSize.getHeight() - 10,
    );
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth - 14,
      doc.internal.pageSize.getHeight() - 10,
      { align: "right" },
    );
  }

  const filename = `capsule-${capsule.name.replace(/[^a-z0-9]/gi, "-").toLowerCase()}.pdf`;
  doc.save(filename);
}

export function exportShoppingListToPDF(
  list: { name: string },
  items: Item[],
) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  doc.text("Closana", 14, 15);

  doc.setFontSize(20);
  doc.setTextColor(30, 30, 30);
  doc.text(list.name, 14, 28);

  let y = 36;
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`${items.length} ${items.length === 1 ? "item" : "items"}`, 14, y);
  y += 10;

  const footnotes: { index: number; url: string }[] = [];

  if (items.length > 0) {
    const itemRows = items.map((item, idx) => {
      let priceStr = "-";
      if (item.price) {
        const parsed = parseFloat(item.price);
        priceStr = isNaN(parsed) ? item.price : `$${parsed.toFixed(2)}`;
      }
      let nameStr = item.name;
      if (item.productLink) {
        footnotes.push({ index: idx + 1, url: item.productLink });
        nameStr = `${item.name} [${idx + 1}]`;
      }
      return [
        "[ ]",
        nameStr,
        item.category,
        item.color || "-",
        item.size || "-",
        priceStr,
      ];
    });

    autoTable(doc, {
      startY: y,
      head: [["", "Item", "Category", "Color", "Size", "Price"]],
      body: itemRows,
      theme: "grid",
      headStyles: { fillColor: [80, 80, 80], fontSize: 9 },
      bodyStyles: { fontSize: 9 },
      margin: { left: 14, right: 14 },
      columnStyles: {
        0: { cellWidth: 12, halign: "center" },
        1: { cellWidth: 45 },
        5: { cellWidth: 22, halign: "right" },
      },
    });

    y = (doc as any).lastAutoTable.finalY + 8;

    const totalPrice = items.reduce((sum, item) => {
      if (item.price) {
        const parsed = parseFloat(item.price);
        if (!isNaN(parsed)) return sum + parsed;
      }
      return sum;
    }, 0);

    if (totalPrice > 0) {
      doc.setFontSize(11);
      doc.setTextColor(30, 30, 30);
      doc.text(`Total: $${totalPrice.toFixed(2)}`, pageWidth - 14, y, { align: "right" });
      y += 10;
    }
  }

  if (footnotes.length > 0) {
    if (y > 260) {
      doc.addPage();
      y = 20;
    }
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    doc.text("Product Links:", 14, y);
    y += 5;
    doc.setFontSize(7);
    doc.setTextColor(100, 100, 130);
    for (const fn of footnotes) {
      if (y > 280) {
        doc.addPage();
        y = 20;
      }
      const linkText = `[${fn.index}] ${fn.url}`;
      doc.text(linkText, 14, y, { maxWidth: pageWidth - 28 });
      y += 4;
    }
  }

  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by Closana on ${new Date().toLocaleDateString()}`,
      14,
      doc.internal.pageSize.getHeight() - 10,
    );
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth - 14,
      doc.internal.pageSize.getHeight() - 10,
      { align: "right" },
    );
  }

  const filename = `shopping-list-${list.name.replace(/[^a-z0-9]/gi, "-").toLowerCase()}.pdf`;
  doc.save(filename);
}
